name = "Makoto Hugo"
description = "A theme inspired by Makoto Fujirama, adapted from Beautiful Hugo (itself based on Beautiful Jekyll)."
features = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]
license = "MIT"
licenselink = "https://github.com/jlumbroso/makoto-hugo/blob/master/LICENSE"
min_version = 0.48
tags = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]

[author]
    name = "jlumbroso"
    homepage = "https://github.com/jlumbroso"

# If Porting existing theme
[original]
    author =  "halogenica"
    homepage = "https://halogenica.net"
    repo = "https://github.com/halogenica/Hugo-BeautifulHugo"
