description = "A theme adapted from Beautiful Hugo (itself based on Beautiful Jekyll)."
features = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]
license = "MIT"
licenselink = "https://github.com/jlumbroso/sweetb-hugo/blob/master/LICENSE"
min_version = 0.48
name = "SweetBSite"
tags = [
  "blog",
  "company",
  "portfolio",
  "projects",
  "minimal",
  "responsive",
  "seo",
  "google analytics",
  "bootstrap",
  "disqus",
  "light",
  "syntax highlighting",
  "multilingual",
  "portfolio",
  "projects",
  "mobile",
  "technical",
]

[author]
homepage = "https://github.com/jlumbroso"
name = "jlumbroso"

# If Porting existing theme
[original]
author = "halogenica"
homepage = "https://halogenica.net"
repo = "https://github.com/halogenica/Hugo-BeautifulHugo"
